version: '3.7'

services:

  namenode:
    image: apache/hadoop:3.3.5
    container_name: namenodeJob
    hostname: namenode
    # si le dossier name n'a pas d'images, on formate et ensuite on lance le namenode
    command: ["bash", "-c", "if [ ! -d /tmp/hadoop-root/dfs/name/current ]; then hdfs namenode -format -nonInteractive; fi && hdfs namenode -fsck -format || true && hdfs namenode"]
    ports:
      - "9870:9870"  # Port du web de hadoop ou du nameNode
      - "8020:8020" 
    env_file:
      - ../Datalakes/config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - ./namenode:/tmp/hadoop-root/dfs/name  # nos metadonnées sont exposé a namenode
      - ./logs:/logs # exposé des logs en hote
    networks:
      - offres_emplois_dakar

# Ici, nous allons utiliser 2 datanode 

#####------------------ datanode1 ------------------------------
  datanode1:
    image: apache/hadoop:3.3.5
    container_name: datanodeJob1
    hostname: datanode1 
    command: ["bash","-c", "hdfs datanode"]
    ports:
      - "9864:9864" # port web ou est exposé le datanode Info
      - "9866:9866"
      - "9867:9867"
    env_file:
      - ../Datalakes/config
    volumes:
      - ./data_node1:/tmp/hadoop-root/dfs/data #données 
      - ./logs:/logs
    depends_on:
      - namenode
    networks:
      - offres_emplois_dakar

####------------------------datanode2-----------------------
  datanode2:
    image: apache/hadoop:3.3.5
    container_name: datanodeJob2
    hostname: datanode2
    command: ["bash","-c", "hdfs datanode"]
    ports:
      - "9874:9864" # port web ou est exposé le datanode Info
      - "9876:9866"
      - "9877:9867"
    env_file:
      - ../Datalakes/config
    volumes:
      - ./data_node2:/tmp/hadoop-root/dfs/data #données 
      - ./logs:/logs
    depends_on:
      - namenode
    networks:
      - offres_emplois_dakar



#-------------Nos gerants ----(Les bosses)-------------------### 
  resourcemanager:
    image: apache/hadoop:3.3.5
    container_name: ressource_Job
    hostname: resourcemanager
    command: ["bash", "-c", "yarn resourcemanager"]
    ports:
      - "8088:8088"
    env_file:
      - ../Datalakes/config
    volumes:
      - ../Datalakes/test.sh:/opt/test.sh
      - ./yarn_logs:/opt/hadoop/yarn-logs
      - ./logs:/logs
    depends_on:
      - namenode
    networks:
      - offres_emplois_dakar

  nodemanager:
    image: apache/hadoop:3.3.5
    container_name: node_managerJob
    hostname: nodemanager
    command: ["bash", "-c", "yarn nodemanager"]
    env_file:
      - ../Datalakes/config
    volumes:
      - ./yarn_logs:/opt/hadoop/yarn-logs
      - ./logs:/logs
    depends_on:
      - namenode
      - resourcemanager
    networks:
      - offres_emplois_dakar
    


 #####--------------- Probleme --------------------------#### 
 ##
 ###     Pour data_node1, namenode et data_node2 
 ##
 ### autoriser hadoop les permissions d'ecrire et autre ... etc 
 ###
 #####----- sudo chmod 775 -R  ./data_node1 ... --- etc 