FROM spark:3.5.7-scala2.12-java11-ubuntu

USER root

# Ici on fait un RUN global 
# Au moment de la creation de l'image, toutes couches auront des versions convenables pour mieux fonctioner
RUN set -ex; \
    apt-get update; \
    apt-get install -y python3 python3-pip; \
    pip install --no-cache-dir jupyter findspark pyspark; \
    mkdir -p /home/spark && \ 
    chown -R spark:spark /home/spark && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir pandas==2.1.1
# Variables d'environnement, ici c'est l'endroit dans le container ou est stocker nos fichiers .ipynb 
# t'as capté 
ENV HOME=/home/spark
ENV PATH=$PATH:$HOME/.local/bin
ENV JAVA_HOME=/opt/java/openjdk
#ENV PATH=$JAVA_HOME/bin:$PATH
ENV SPARK_HOME=/opt/spark
ENV HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
ENV PATH=$SPARK_HOME/bin:$PATH


USER spark
WORKDIR /home/spark

EXPOSE 8888

# On lance note jupyter à l'addresse suivant 
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser"]