version: '3.8'

# services:

include:
    - ./Airflow/docker-compose.airflow.yaml
    - ./basesDeDonnees/docker-compose.databases.yaml
    - ./Datalakes/docker-compose.lake.yaml
    - ./DataWarehouse/docker-compose.warehouse.yaml
    - ./Dash/docker-compose.dash.yaml
    - ./Fastapi/docker-compose.fast.yaml
    
    #- ./Spark/docker-compose.spark.yaml


networks:
    offres_emplois_dakar:
        external: true




#######---------------------------------------------#####
                # probleme rencontré 
######-------------------------------------------------######

# Faut verifier si le network est creer par prune
# si c'est pas le cas, faut le creer manuellement, en utilisant la commande suivante 
           
        # sudo docker network create offres_emplois_dakar




