version: '3.7'

# services:

include:
    - ./Airflow/docker-compose.airflow.yaml
    - ./basesDeDonnees/docker-compose.databases.yaml
    - ./Datalakes/docker-compose.lake.yaml


networks:
    offres_emplois_dakar:
        external: true
     
#--------------#
# probleme 
#-------------#
# Faut verifier si le network est creer par prune
# si c'est pas le cas, faut le creer manuellement 
# sudo docker network create offres_emplois_dakar




